### ISSUE TITLE
ローカルのファイルを読み出して再生する機能を作る

### ISSUE THREAD

**Issue by yumetodo** [YuichirouSeitoku/mdd#2]

**Comment by yumetodo** [comment]
https://github.com/yuseisui/electron-video-player

参考になりそう。

**Comment by gauzesya** [comment]
メモ:  ローカルにある動画ファイルの再生

- CSPに`media-src 'self' blob:`を設定する必要あり
- rendererプロセスだけで完結させるには`nodeINtegration: true`にする必要がある
